### ISSUE TITLE
google social login

### ISSUE THREAD

**Issue by cshooon** [LlamaVista/LlamaVista#37]
<img width="350" alt="Screenshot 2024-02-14 at 4 36 57 PM" src="https://github.com/LlamaVista/LlamaVista/assets/113033780/ddcba5dc-5232-4b89-8af5-4dce2dcbc71e">
<img width="300" alt="Screenshot 2024-02-14 at 4 37 10 PM" src="https://github.com/LlamaVista/LlamaVista/assets/113033780/fc84173d-a1da-4189-bf16-f498e20a5602">
<img width="1579" alt="Screenshot 2024-02-14 at 4 37 23 PM" src="https://github.com/LlamaVista/LlamaVista/assets/113033780/8f0cac70-ec4e-4eed-ac38-639097c90e59">

프론트에서 code 받아서 access token과 refresh token 받는 url입니다.

요청 예시: 
http://techvista24.com:8000/callback?code=4%2F0AeaYSHDj9I5MIN6E4JM9BBILWJRugwFFzzLQsAp5EMuv0fbvuMMgxUQwA2WIXnDCXDsHRg

다시 짰는데 처음 짠 거랑 코드가 똑같아요... (맨 처음이요) 그 때 왜 안 됬었나요??

**Comment by seo-seoungjun** [comment]
400 에러 발생하네요 ㅠ "Failed to exchange authorization code for tokens"

**Comment by seo-seoungjun** [comment]
<img width="324" alt="스크린샷 2024-02-15 오후 6 35 32" src="https://github.com/LlamaVista/LlamaVista/assets/79730690/e56ace2f-2e92-484f-89a3-c2ccd3fe2a9e">

코드받아서 위 처럼 요청보낸거죠..?

**Comment by seo-seoungjun** [comment]
1. code, token 발급을 받는 리다이렉션 루트 url을 일치시키기 위해 프론트 서버를 http://techvista24.com:3000으로 올리기 (https://github.com/MomenSherif/react-oauth/issues/12#issuecomment-1131408898 참고)
2. 백엔드에서 응답받는 리다이렉션 url을 https로 변환하기 (https://techvista24.com:8000/callback)
3. 프론트에서 리프레쉬, 접근 토큰 발급 / 백엔드에서 토큰을 통해 유저 정보를 발급
4. 백엔드에서 유저 정보발급까지 전부 진행
5. 프론트에서 유저 정보발급까지 전부 진행

**Comment by seo-seoungjun** [comment]
5번 => 3번 => 3번 안될시에 1번
@cshooon 이렇게 하면 좋을 것 같습니다
